version: '3.7'

services:
  # development environment for SAML-COS
  saml-cos:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    image: saml-cos:dev
    container_name: saml-cos
    command: --ISCAgent false
    ports:
    - "51773:1972"
    - "52773:52773"
    volumes:
    - .:/app
